export type Project = { slug: string; title: string; subtitleZh: string; subtitleEn: string; year: string; duration: string; roleZh: string; roleEn: string; descriptionZh: string; descriptionEn: string; cover: string; pages: number[]; accent: string; };

export const projects: Project[] = [
  { slug: "ego-data-collection", title: "EGO", subtitleZh: "面向物理 AI 数据采集的一体化可穿戴硬件系统", subtitleEn: "Multimodal Data Collection System", year: "2026", duration: "2 months", roleZh: "团队项目 · 设计负责人", roleEn: "Group Work · Design Lead", descriptionZh: "系统通过人体穿戴和手持设备采集第一视角、腕部近场及操作过程数据，无需依赖机器人本体，有助于更灵活地进入真实场景并扩大数据采集规模。", descriptionEn: "A wearable and handheld hardware ecosystem for capturing first-person, wrist-level and task-process data without relying on a robot body, enabling flexible real-world deployment and scalable data collection.", cover: "/projects/pages/slide-42.webp", pages: Array.from({ length: 18 }, (_, i) => i + 42), accent: "#3d90a9" },
  { slug: "nano-at", title: "NANO AT", subtitleZh: "微型真空抽气泵", subtitleEn: "Miniature Vacuum Pump", year: "2025", duration: "2 months", roleZh: "团队项目 · 设计负责人", roleEn: "Group Work · Design Lead", descriptionZh: "面向居家收纳场景的微型真空设备，以小巧体积、可控噪音和克制的视觉语言，改善传统抽气泵效率低、噪音大且难以融入家居环境的问题。", descriptionEn: "A compact vacuum device for home storage, designed around a quieter experience and restrained visual language to improve on bulky, noisy conventional pumps.", cover: "/projects/pages/slide-05.webp", pages: Array.from({ length: 16 }, (_, i) => i + 5), accent: "#e78927" },
  { slug: "evo-tire-pump", title: "EVO TIRE PUMP 200", subtitleZh: "电动便携式轮胎充气泵", subtitleEn: "Portable Electric Tire Inflator", year: "2025", duration: "4 months", roleZh: "团队项目 · 设计负责人", roleEn: "Group Work · Design Lead", descriptionZh: "面向汽车、摩托车及自行车用户的便携式充气泵，通过紧凑一体化结构、压力检测、数显交互、预设胎压与自动停止功能，提升户外及紧急场景下的使用效率。", descriptionEn: "A portable inflator for cars, motorcycles and bicycles, combining a compact integrated form with pressure sensing, digital interaction, preset pressure and automatic stop.", cover: "/projects/pages/slide-21.webp", pages: Array.from({ length: 5 }, (_, i) => i + 21), accent: "#5f8d5f" },
  { slug: "interface-footwear", title: "INTERFACE", subtitleZh: "模块化鞋类系统", subtitleEn: "Modular Footwear System", year: "2026", duration: "2 weeks", roleZh: "个人项目", roleEn: "Individual Project", descriptionZh: "以工业设计方法构建鞋身与功能鞋底的模块化系统，通过快速连接结构，让用户根据通勤、运动训练与户外活动等场景自由切换鞋底模块。", descriptionEn: "A modular footwear system separating the upper from functional sole units, using a quick-connect structure to adapt between commuting, training and outdoor scenarios.", cover: "/projects/pages/slide-26.webp", pages: Array.from({ length: 16 }, (_, i) => i + 26), accent: "#cc2929" },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
